### ISSUE TITLE
Wording on number 5

### ISSUE THREAD

**Issue by ryans-git** [learn-co-curriculum/swift-functionLab-lab#3]
"After you print the variable once, assign it to a new variable on the next line."

is this supposed to be "assign it to a new value on the next line"? or are we just supposed to make a new variable and then print that variable in the function too?

**Comment by JimCampagno** [comment]
@ryan1twice 👍 

Good find. Thanks. It should read as "After you print the variable once, assign a new value to this variable on the next line". I've updated the playground file to reflect this now for any students moving forward.
